name: Ingest Preview (PR)

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  preview-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.1.0
        with:
          node-version: ${{ vars.NODE_VERSION }} # Set in repo variables (Settings > Secrets and variables > Actions)
          cache: npm

      - name: SLSA supply chain protection
        uses: ministryofjustice/devsecops-actions/sca/slsa@79b9f7c4bd0d3cb85d4f7a289a515a666d38322e

      - name: Install dependencies
        run: npm ci

      - name: Ingest content
        run: node scripts/ingest.mjs

      - name: Build
        run: npm run build
